---
- name: Testing ansible stuff
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Print something
      ansible.builtin.debug:
        msg: "Hello from ansible"

    - name: Print information
      ansible.builtin.debug:
        var: ansible_distribution


    - name: Print information fully
      ansible.builtin.debug:
        var: ansible_facts.distribution
